<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class CostAttributesTest extends TestCase
{
    use DatabaseTransactions;

    /** @var \App\Project */
    protected $project;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->project = factory('App\Project');
    }

    public function test_material_remaining_unit_price_with_current()
    {
        $breakdownResource = factory(App\BreakdownResource::class)->create();

        $shadow = \App\BreakDownResourceShadow::whereBreakdownResourceId($breakdownResource->id);


    }

    /*public function test_material_remaining_unit_price_with_todate()
    {

    }

    public function test_not_started_material_remaining_unit_price()
    {

    }

    public function test_other_remaining_unit_price_with_current()
    {

    }

    public function test_other_remaining_unit_price_with_todate()
    {

    }

    public function test_not_started_other_remaining_unit_price()
    {

    }*/
}
